name: Quote workflow
on:
    schedule: # Run workflow automatically
        - cron: '0 * * * *' # Runs every hour, on the hour
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-quote:
    name: Update this repo's README with amazing quotes
    runs-on: ubuntu-latest
    steps:
       - name: Setup node 14
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
            node-version: 14.x
       - name: pull script to get quote
       - uses: jhamadhav/quote-workflow@master
       - name: Commit and push changes
         run: |
            git config --global user.name "jhamadhav"
            git config --global user.email "contact@jhamadhav.com"
            git add -A
            git commit -m "New Quote update"
            git push```
